// 物理卡牌对战 - 卡牌数据 v4.0
// 对齐原始 v3.24 设计：53攻 + 34辅 + 5域 + 14召 + 3相 = 109张
// 生成日期: 2026-06-09
const CARDS = [
  {
    id: "A01",
    name: "重力锤击",
    type: "attack",
    domain: ["力"],
    cost: 12,
    description: "造成75点伤害。原理：物体所受重力与质量成正比（G=mg），质量越大重力越强。",
    formula: "G=mg",
    rarity: "common",
    effect: {"dmg":75}
  },
  {
    id: "A02",
    name: "惯性冲锋",
    type: "attack",
    domain: ["力"],
    cost: 14,
    description: "造成50点基础伤害 + 上回合己方力系攻击伤害的50%。下回合继续造成本次即时伤害的50%（仅延续1回合）。原理：一切物体都有惯性，质量越大运动状态越难改变。",
    formula: "惯性定律",
    rarity: "common",
    effect: {"dmg":50,"inertiaCarry":true,"carryRatio":0.5,"nextCarryRatio":0.5}
  },
  {
    id: "A03",
    name: "压强穿刺",
    type: "attack",
    domain: ["力"],
    cost: 16,
    description: "造成80点伤害，无视本领域防御。原理：受力面积越小压强越大（P=F/S），压强集中可穿透防御。",
    formula: "P=F/S",
    rarity: "common",
    effect: {"dmg":80,"ignoreDefense":true}
  },
  {
    id: "A04",
    name: "杠杆撬击",
    type: "attack",
    domain: ["力"],
    cost: 10,
    description: "造成50点伤害，己方每有一张辅助卡在场额外+30伤害。原理：杠杆平衡条件F1L1=F2L2，辅助卡=支点，越多支点撬动越强。",
    formula: "F1L1=F2L2",
    rarity: "common",
    effect: {"dmg":50,"perSupportBonus":30}
  },
  {
    id: "A05",
    name: "重力势能",
    type: "attack",
    domain: ["力"],
    cost: 14,
    description: "打出后进入蓄能状态（最多4回合），每经过己方1回合蓄能高度+1。对手对己方累计造成200伤害时或持续时间结束时触发：造成(40+蓄能高度×40)伤害。触发后此卡离场。原理：物体质量越大、位置越高，重力势能越大（Ep=mgh）。",
    formula: "Ep=mgh",
    rarity: "rare",
    effect: {"dmg":40,"heightBonus":40,"maxTurns":4,"triggerThreshold":200,"isFieldCard":true}
  },
  {
    id: "A06",
    name: "动能冲击",
    type: "attack",
    domain: ["力"],
    cost: 16,
    description: "造成60点伤害，接下来2个己方回合每回合额外造成30点延续伤害。原理：运动的物体具有动能（Ek=1/2mv²），碰撞后能量持续传递。",
    formula: "Ek=1/2mv²",
    rarity: "common",
    effect: {"dmg":60,"dotDmg":30,"dotTurns":2}
  },
  {
    id: "A08",
    name: "做功打击",
    type: "attack",
    domain: ["力"],
    cost: 15,
    description: "造成50点伤害 + 对方已损失HP的10%额外伤害。原理：力对物体做功W=Fs，力与位移共同决定做功大小——对方损失越多，做功效果越显著。",
    formula: "W=Fs",
    rarity: "common",
    effect: {"dmg":50,"hpLossBonus":0.1}
  },
  {
    id: "A09",
    name: "超声清洗",
    type: "attack",
    domain: ["声"],
    cost: 15,
    description: "造成55点伤害 + 消灭对方一张驻场卡（若无驻场卡则仅造成伤害）。原理：超声波空化效应——空化气泡破裂产生强大冲击力，能清除表面附着物。",
    formula: "超声波空化",
    rarity: "common",
    effect: {"dmg":55,"destroyField":true}
  },
  {
    id: "A10",
    name: "次声震荡",
    type: "attack",
    domain: ["声"],
    cost: 20,
    description: "造成45点即时伤害。持续5个己方回合，每回合结算阶段造成递增伤害：15/25/35/45/55。视为驻场卡，可被清场效果清除。原理：次声波频率<20Hz，与人体器官固有频率接近，引发共振，伤害逐步增大。",
    formula: "次声共振",
    rarity: "rare",
    effect: {"dmg":45,"dotSequence":[15,25,35,45,55],"isFieldCard":true}
  },
  {
    id: "A11",
    name: "啸叫",
    type: "attack",
    domain: ["声"],
    cost: 14,
    description: "造成20点即时伤害。打出后驻场5回合，每回合递增伤害：20→30→40→50→60。视为驻场卡，可被清场效果清除。原理：声反馈啸叫——话筒靠近音箱产生正反馈循环，声音逐圈放大。",
    formula: "声反馈",
    rarity: "rare",
    effect: {"dmg":20,"dotSequence":[20,30,40,50,60],"isFieldCard":true}
  },
  {
    id: "A13",
    name: "驻波共振",
    type: "attack",
    domain: ["声"],
    cost: 16,
    description: "造成70点伤害，己方场上每有一张持续生效的声系卡伤害+25。原理：驻波由入射波和反射波叠加形成，反射面越多共振效果越强。",
    formula: "驻波叠加",
    rarity: "common",
    effect: {"dmg":70,"perSoundFieldBonus":25}
  },
  {
    id: "A14",
    name: "回声爆破",
    type: "attack",
    domain: ["声"],
    cost: 13,
    description: "本回合造成0伤害，下回合己方出牌阶段开始时造成100点伤害。原理：回声是声音遇到障碍物反射回来的现象，传播需要时间延迟——但返回时能量集中爆发。",
    formula: "回声延迟",
    rarity: "common",
    effect: {"dmg":0,"delayedDmg":100,"delayTurns":1}
  },
  {
    id: "A45",
    name: "双耳定位",
    type: "attack",
    domain: ["声"],
    cost: 12,
    description: "造成50点伤害 + 查看对方2张手牌。原理：双耳效应——两耳接收到声音的时间差和强度差使人能精确定位声源方向。",
    formula: "双耳效应",
    rarity: "common",
    effect: {"dmg":50,"viewHand":2}
  },
  {
    id: "A15",
    name: "激光切割",
    type: "attack",
    domain: ["光"],
    cost: 25,
    description: "造成120点伤害。原理：激光方向性好、能量高度集中，几乎不发散，适合精确切割。",
    formula: "激光特性",
    rarity: "common",
    effect: {"dmg":120}
  },
  {
    id: "A16",
    name: "色散分解",
    type: "attack",
    domain: ["光"],
    cost: 20,
    description: "造成40点即时伤害。驻场4个己方回合，每回合结算阶段造成40点伤害。若未被清场，回到手牌可0费再次打出。原理：白光通过三棱镜色散为七色光，各色光独立作用后重新合成白光——光的可逆循环。",
    formula: "色散",
    rarity: "rare",
    effect: {"dmg":40,"dotDmg":40,"dotTurns":4,"returnOnSurvive":true,"isFieldCard":true}
  },
  {
    id: "A17",
    name: "红外灼烧",
    type: "attack",
    domain: ["光"],
    cost: 15,
    description: "造成48点伤害 + 为对方附加1层灼烧。原理：红外线具有显著的热效应，能使物体温度升高。",
    formula: "红外线热效应",
    rarity: "common",
    effect: {"dmg":48,"burn":1}
  },
  {
    id: "A18",
    name: "紫外灭杀",
    type: "attack",
    domain: ["光"],
    cost: 16,
    description: "造成50点伤害 + 消灭对方一张驻场卡（若无驻场卡则仅造成伤害）。原理：紫外线具有杀菌消毒作用，能破坏微生物的DNA结构。",
    formula: "紫外线杀菌",
    rarity: "common",
    effect: {"dmg":50,"destroyField":true}
  },
  {
    id: "A19",
    name: "光纤穿透",
    type: "attack",
    domain: ["光"],
    cost: 18,
    description: "无视本领域防御，造成100点伤害。原理：光在光纤中通过全反射传播，几乎无能量损耗。",
    formula: "全反射",
    rarity: "common",
    effect: {"dmg":100,"ignoreDefense":true}
  },
  {
    id: "A20",
    name: "日光暴晒",
    type: "attack",
    domain: ["光"],
    cost: 16,
    description: "造成80点伤害 + 清除己方1种负面状态 + 己方场上每有一张辅助卡额外+20伤害。原理：阳光中的紫外线具有杀菌消毒作用，暴晒越久清除效果越强。",
    formula: "太阳辐射",
    rarity: "common",
    effect: {"dmg":80,"clearDebuff":1,"perSupportBonus":20}
  },
  {
    id: "A46",
    name: "折射偏转",
    type: "attack",
    domain: ["光"],
    cost: 17,
    description: "造成70点伤害 + 己方选择将对方一张驻场卡弹回手牌（若无驻场卡则仅造成伤害）。原理：光从一种介质进入另一种介质时方向偏转——利用折射偏转对方驻场。",
    formula: "光的折射",
    rarity: "common",
    effect: {"dmg":70,"bounceField":true}
  },
  {
    id: "A55",
    name: "凸透引燃",
    type: "attack",
    domain: ["光","热"],
    cost: 12,
    description: "造成38点伤害 + 己方场上每有一张辅助卡，为对方附加1层灼烧（上限3层）。原理：凸透镜将平行光聚焦于一点，焦点处温度极高足以引燃物体。辅助卡=透镜，越多透镜聚焦越强。",
    formula: "凸透镜聚焦",
    rarity: "rare",
    effect: {"dmg":38,"perSupportBurn":1,"maxBurn":3}
  },
  {
    id: "A21",
    name: "烈焰灼蚀",
    type: "attack",
    domain: ["热","力"],
    cost: 15,
    description: "造成80点伤害，对方每有1层灼烧额外+15伤害（灼烧保留）。原理：热传导使高温持续向低温传递，灼烧越猛烈侵蚀越深。",
    formula: "热传导",
    rarity: "rare",
    effect: {"dmg":80,"perBurnBonus":15}
  },
  {
    id: "A22",
    name: "热对流",
    type: "attack",
    domain: ["热"],
    cost: 14,
    description: "造成65点伤害 + 为对方附加1层灼烧 + 己方盲选对方一张手牌弹回牌库顶部。原理：热对流是流体中温度不同的部分相对运动传递热量——伴随流体运动，持续传热且扰乱对方部署。",
    formula: "热对流",
    rarity: "rare",
    effect: {"dmg":65,"burn":1,"bounceHand":1}
  },
  {
    id: "A23",
    name: "热辐射",
    type: "attack",
    domain: ["热"],
    cost: 20,
    description: "造成80点伤害 + 为对方附加1层灼烧。原理：热辐射不需要介质，真空也能传热，持续照射产生持续灼伤。",
    formula: "热辐射",
    rarity: "common",
    effect: {"dmg":80,"burn":1}
  },
  {
    id: "A24",
    name: "熔岩喷发",
    type: "attack",
    domain: ["热"],
    cost: 18,
    description: "造成70点伤害 + 为对方附加2层灼烧 + 对方下2回合精神力恢复-3（叠加最低到0）。原理：岩浆温度极高，持续灼烧并改变周围环境。",
    formula: "火山喷发",
    rarity: "rare",
    effect: {"dmg":70,"burn":2,"spiritDebuff":-3,"debuffTurns":2}
  },
  {
    id: "A25",
    name: "蒸发消散",
    type: "attack",
    domain: ["热"],
    cost: 17,
    description: "造成65点伤害 + 为对方附加1层灼烧 + 偷取对方15精神力 + 消灭对方一张驻场卡（若无驻场卡则仅造成伤害和偷取）。原理：蒸发是物质从液态变气态的相变过程——辅助效果随蒸发而消散。",
    formula: "蒸发",
    rarity: "rare",
    effect: {"dmg":65,"burn":1,"stealSpirit":15,"destroyField":true}
  },
  {
    id: "A26",
    name: "凝固封锁",
    type: "attack",
    domain: ["热"],
    cost: 0,
    description: "消耗对方2层灼烧，造成60点伤害，对方下回合无法出牌。原理：凝固是放热过程，消耗灼烧能量转化为封锁力。",
    formula: "凝固放热",
    rarity: "epic",
    condition: "消耗对方2层灼烧",
    effect: {"dmg":60,"consumeBurn":2,"turnBlock":true}
  },
  {
    id: "A47",
    name: "升华爆散",
    type: "attack",
    domain: ["热"],
    cost: 18,
    description: "造成63点伤害 + 为对方附加1层灼烧 + 己方恢复30HP。原理：升华是固体直接变气体的相变过程，急剧膨胀释放能量，同时吸收大量热量——爆炸伤人又降温自愈。",
    formula: "升华吸热",
    rarity: "common",
    effect: {"dmg":63,"burn":1,"heal":30}
  },
  {
    id: "A54",
    name: "爆燃",
    type: "attack",
    domain: ["热"],
    cost: 12,
    description: "造成40点伤害 + 引爆对方所有灼烧层数，每层引爆造成50点伤害，引爆后灼烧层数归零。原理：气体受热急剧膨胀可引发爆炸，将累积的热能瞬间释放。",
    formula: "热膨胀",
    rarity: "rare",
    effect: {"dmg":40,"detonateBurn":true,"perBurnDmg":50}
  },
  {
    id: "A27",
    name: "闪电劈击",
    type: "attack",
    domain: ["电"],
    cost: 10,
    description: "造成30点伤害。场上电系辅助卡≥2张时触发：无视20点本领域防御+额外20伤害。原理：电压足够高时可击穿绝缘层——高压击穿。",
    formula: "高压击穿",
    rarity: "rare",
    effect: {"dmg":30,"triggerElectric2":{"ignoreDefense":20,"bonusDmg":20}}
  },
  {
    id: "A28",
    name: "雷暴链击",
    type: "attack",
    domain: ["电"],
    cost: 9,
    description: "造成30点伤害。场上电系辅助卡≥1张时触发连锁：对方场上每有1张辅助卡额外造成15伤害。原理：放电沿最低阻抗路径传导，辅助卡成为导电路径——越多路径伤害越高。",
    formula: "链式放电",
    rarity: "rare",
    effect: {"dmg":30,"triggerElectric1":{"chainPerSupport":15}}
  },
  {
    id: "A29",
    name: "电弧灼烧",
    type: "attack",
    domain: ["电"],
    cost: 9,
    description: "造成30点伤害。场上电系辅助卡≥1张时触发：额外造成20点灼烧伤害。原理：电流热效应Q=I²Rt，大电流通过空气产生高温电弧。",
    formula: "Q=I²Rt",
    rarity: "common",
    effect: {"dmg":30,"triggerElectric1":{"bonusDmg":20}}
  },
  {
    id: "A30",
    name: "电磁脉冲",
    type: "attack",
    domain: ["电"],
    cost: 10,
    description: "造成30点伤害。场上电系辅助卡≥2张时触发：消灭对方一张驻场卡 + 额外15伤害（若无驻场卡则仅加伤）。原理：EMP电磁脉冲能干扰和瘫痪运行中的电子系统。",
    formula: "电磁脉冲",
    rarity: "rare",
    effect: {"dmg":30,"triggerElectric2":{"destroyField":true,"bonusDmg":15}}
  },
  {
    id: "A44",
    name: "火花放电",
    type: "attack",
    domain: ["电"],
    cost: 8,
    description: "造成30点伤害，最基础的电系攻击元件。原理：最基本的放电现象，纯电路元件——无附加效果但费用最低。",
    formula: "放电现象",
    rarity: "common",
    effect: {"dmg":30}
  },
  {
    id: "A48",
    name: "静电爆发",
    type: "attack",
    domain: ["电"],
    cost: 8,
    description: "造成30点伤害。若本回合对方已受到过电系伤害，额外+25伤害。原理：静电积累到阈值后突然放电——前面已有电流导通，后续爆发更强。",
    formula: "静电放电",
    rarity: "common",
    effect: {"dmg":30,"afterElectricDmg":25}
  },
  {
    id: "A49",
    name: "过载放电",
    type: "attack",
    domain: ["电"],
    cost: 10,
    description: "造成30点伤害。场上电系辅助卡≥3张时触发：本次基础伤害翻倍（30→60），触发后摧毁己方1张电系辅助卡。原理：超额定电压运行导致过载输出，元件因过热而损坏。",
    formula: "过载原理",
    rarity: "common",
    effect: {"dmg":30,"triggerElectric3":{"doubleDmg":true,"destroyElectricSupport":1}}
  },
  {
    id: "A31",
    name: "共振爆破",
    type: "attack",
    domain: ["声","力"],
    cost: 20,
    description: "造成50点伤害 + 对方场上每有一张卡额外造成55伤害。原理：共振是受迫振动达到固有频率时振幅最大的现象——对方场上卡越多=共振面越多=破坏力越强。",
    formula: "共振",
    rarity: "rare",
    effect: {"dmg":50,"perOppFieldCard":55}
  },
  {
    id: "A32",
    name: "声波推力",
    type: "attack",
    domain: ["声","力"],
    cost: 15,
    description: "造成80点伤害，若场上有力领域则额外造成40伤害。原理：声波是机械波，本质是介质中质点的振动——振动传递力的作用，有力领域加持则推力更强。",
    formula: "声波是机械波",
    rarity: "rare",
    effect: {"dmg":80,"forceDomainBonus":40}
  },
  {
    id: "A33",
    name: "冲击波",
    type: "attack",
    domain: ["声","力"],
    cost: 19,
    description: "造成100点伤害 + 对方下回合每张卡精神力消耗+3。原理：冲击波是剧烈的声波，波前推动空气产生巨大压力，使对方行动迟缓（消耗增加）。",
    formula: "冲击波",
    rarity: "rare",
    effect: {"dmg":100,"opponentExtraCost":3}
  },
  {
    id: "A34",
    name: "摩擦生热",
    type: "attack",
    domain: ["热","力"],
    cost: 15,
    description: "造成60点伤害 + 为对方附加1层灼烧 + 偷取对方20精神力。原理：摩擦力做功产生热量Q=fs，做功越多热量越大——既灼伤对方又消耗其能量。",
    formula: "Q=fs",
    rarity: "rare",
    effect: {"dmg":60,"burn":1,"stealSpirit":20}
  },
  {
    id: "A43",
    name: "活塞压缩",
    type: "attack",
    domain: ["力","热"],
    cost: 13,
    description: "造成41点伤害 + 为对方附加1层灼烧 + 对方下回合每张卡精神力消耗+5。原理：活塞对气体做功，压缩使气体温度升高——做功转化为内能，温度升高产生灼烧和压制。",
    formula: "压缩升温",
    rarity: "rare",
    effect: {"dmg":41,"burn":1,"opponentExtraCost":5}
  },
  {
    id: "A35",
    name: "短路熔毁",
    type: "attack",
    domain: ["电","力","热"],
    cost: 20,
    description: "消灭对方一张召唤物（无视HP直接击杀）；若对方无召唤物则造成80伤害。原理：短路时电流剧增，热效应Q=I²Rt使导体瞬间熔化——物理性摧毁。",
    formula: "Q=I²Rt短路",
    rarity: "epic",
    effect: {"dmg":80,"destroySummon":true}
  },
  {
    id: "A36",
    name: "焦耳热击",
    type: "attack",
    domain: ["热","电"],
    cost: 18,
    description: "造成57点伤害 + 为对方附加1层灼烧 + 对方下2回合精神力恢复-3（叠加最低到0）。原理：焦耳定律Q=I²Rt，电流通过电阻产生热量——持续灼烧并压制恢复。",
    formula: "Q=I²Rt",
    rarity: "rare",
    effect: {"dmg":57,"burn":1,"spiritDebuff":-3,"debuffTurns":2}
  },
  {
    id: "A37",
    name: "漏电灼伤",
    type: "attack",
    domain: ["热","电"],
    cost: 14,
    description: "造成44点伤害 + 为对方附加1层灼烧。原理：漏电使电流持续通过非预期路径释放能量，电能转化为热能造成灼伤。",
    formula: "漏电发热",
    rarity: "rare",
    effect: {"dmg":44,"burn":1}
  },
  {
    id: "A38",
    name: "光压推击",
    type: "attack",
    domain: ["光","力"],
    cost: 15,
    description: "造成70点伤害 + 己方选择将对方一张驻场卡弹回手牌（若无驻场卡则盲选对方一张手牌放回牌库最上方）。原理：光子具有动量，照射物体表面产生光压——虽微小但确实存在推力。",
    formula: "光压",
    rarity: "rare",
    effect: {"dmg":70,"bounceField":true,"fallbackBounceHand":true}
  },
  {
    id: "A39",
    name: "光电效应",
    type: "attack",
    domain: ["光","电"],
    cost: 18,
    description: "造成80点伤害 + 选择己方场上一张持续生效的光系卡，该卡同时视为电系卡（保留光系标签，新增电系标签），持续至该卡离场。若无光系驻场卡则仅造成伤害。原理：光子能量足够大时可使金属表面电子逸出——光能转化为电能。",
    formula: "光电效应",
    rarity: "rare",
    effect: {"dmg":80,"dualDomain":{"from":"光","to":"电"}}
  },
  {
    id: "A52",
    name: "光电信号",
    type: "attack",
    domain: ["光","电"],
    cost: 18,
    description: "造成60点伤害 + 查看对方全部手牌。原理：光信号可通过光电转换变为电信号传输，从而获取信息。",
    formula: "光电转换",
    rarity: "rare",
    effect: {"dmg":60,"viewHand":"all"}
  },
  {
    id: "A40",
    name: "安培力冲击",
    type: "attack",
    domain: ["力","电"],
    cost: 16,
    description: "造成50点伤害，若己方场上有领域卡则额外+35伤害。原理：通电导线在磁场中受到力的作用——磁场对电流的作用力。",
    formula: "安培力",
    rarity: "rare",
    effect: {"dmg":50,"domainBonus":35}
  },
  {
    id: "A41",
    name: "太阳能聚变",
    type: "attack",
    domain: ["光","热"],
    cost: 28,
    description: "造成140点伤害，若场上有热领域则额外+70伤害。原理：太阳的能量来源于核聚变，释放巨大的光和热——光和热的终极结合。",
    formula: "太阳能",
    rarity: "epic",
    effect: {"dmg":140,"heatDomainBonus":70}
  },
  {
    id: "A50",
    name: "海市蜃楼",
    type: "attack",
    domain: ["光","热"],
    cost: 20,
    description: "造成80点伤害 + 持续4个己方回合内对方每个回合首次攻击30%概率偏转（伤害为0）。原理：地面加热空气产生温差层，热空气使光折射——虚像迷惑对手，攻击可能打偏。",
    formula: "光的折射(热空气)",
    rarity: "rare",
    effect: {"dmg":80,"mirageTurns":4,"mirageChance":0.3}
  },
  {
    id: "A42",
    name: "电声轰鸣",
    type: "attack",
    domain: ["电","声"],
    cost: 16,
    description: "造成80点伤害 + 对方下回合所有精神力恢复效果减半。原理：扬声器原理——电能驱动线圈振动产生声波，电声转换中能量被消耗，对方恢复也受影响。",
    formula: "电声转换",
    rarity: "rare",
    effect: {"dmg":80,"halveSpiritRecovery":true}
  },
  {
    id: "A51",
    name: "声速激增",
    type: "attack",
    domain: ["热","声"],
    cost: 16,
    description: "造成70点伤害，对方每有1层灼烧，己方下次声系攻击+6伤害。原理：声速v=331+0.6t，温度越高声速越快——灼烧代表高温，声速因此激增，下次声系攻击更强。",
    formula: "v=331+0.6t",
    rarity: "rare",
    effect: {"dmg":70,"perBurnNextSound":6}
  },
  {
    id: "A53",
    name: "镜面回声",
    type: "attack",
    domain: ["声","光"],
    cost: 18,
    description: "造成70点伤害 + 本回合声系和光系攻击卡+10伤害。原理：声波的回声和光的镜面反射本质都是波的反射现象——声光同源，能量叠加。",
    formula: "波的反射",
    rarity: "rare",
    effect: {"dmg":70,"soundLightBonus":10}
  },
  {
    id: "S01",
    name: "质量增大",
    type: "support",
    domain: ["力"],
    cost: 5,
    description: "己方下次力系攻击+10伤害。原理：物体质量越大，重力越大（G=mg），惯性也越大——质量是惯性的唯一量度。",
    formula: "G=mg",
    rarity: "common",
    effect: {"nextForceBonus":10}
  },
  {
    id: "S02",
    name: "能量蓄积",
    type: "support",
    domain: ["力"],
    cost: 5,
    description: "己方下次力系攻击+18伤害。原理：运动的物体具有动能（Ek=1/2mv²），能量蓄积后释放更猛烈。",
    formula: "Ek=1/2mv²",
    rarity: "common",
    effect: {"nextForceBonus":18}
  },
  {
    id: "S03",
    name: "受力面积缩小",
    type: "support",
    domain: ["力"],
    cost: 5,
    description: "己方下次攻击+10伤害。原理：压强P=F/S，受力面积越小压强越大——集中力量于一点。",
    formula: "P=F/S",
    rarity: "common",
    effect: {"nextAtkBonus":10}
  },
  {
    id: "S04",
    name: "摩擦阻碍",
    type: "support",
    domain: ["力"],
    cost: 12,
    description: "对方力系攻击卡伤害-25（持续2个己方回合）。原理：摩擦力阻碍相对运动，是物体运动的主要阻力。",
    formula: "摩擦力",
    rarity: "rare",
    effect: {"forceDefense":25,"turns":2}
  },
  {
    id: "S05",
    name: "力的合成",
    type: "support",
    domain: ["力"],
    cost: 8,
    description: "本回合每打出一张力系攻击卡，该卡伤害+10×（本回合此前已打出的力系攻击卡数量），上限+30。原理：同向力的合成——合力等于各分力之和，越多力叠加越强。",
    formula: "力的合成",
    rarity: "rare",
    effect: {"stackingForceDmg":10,"maxStacking":30}
  },
  {
    id: "S06",
    name: "弹性储能",
    type: "support",
    domain: ["力"],
    cost: 10,
    description: "打出后进入储能状态（场上持续，最多4回合）。己方每打出一张力系攻击卡，将该卡实际造成伤害的30%存入储能（上限300）。时间结束或储能满时释放50%伤害。原理：弹性势能Ep=1/2kx²，弹性形变越大储能越多。",
    formula: "Ep=1/2kx²",
    rarity: "rare",
    effect: {"energyStore":0.3,"maxStore":300,"releaseRatio":0.5,"maxTurns":4,"isFieldCard":true}
  },
  {
    id: "S07",
    name: "回声消声",
    type: "support",
    domain: ["声"],
    cost: 10,
    description: "己方盲选查看对方2张手牌 + 选择清除己方1种负面状态。原理：回声定位产生反相声波，主动降噪（ANC）抵消有害效果。",
    formula: "主动降噪",
    rarity: "rare",
    effect: {"viewHand":2,"clearDebuff":1}
  },
  {
    id: "S08",
    name: "噪音干扰",
    type: "support",
    domain: ["声"],
    cost: 8,
    description: "对方下回合每张卡出牌精神力消耗+5。原理：噪声是环境污染源，干扰人的注意力和判断力。",
    formula: "噪声污染",
    rarity: "common",
    effect: {"opponentExtraCost":5,"turns":1}
  },
  {
    id: "S09",
    name: "频率调节",
    type: "support",
    domain: ["声"],
    cost: 5,
    description: "选择一种：升高则下张声系卡+10伤害；降低则下张声系卡+10伤害（次声震荡持续回合+2）。原理：频率f升高则超声能量集中；f降低则次声与人体共振。",
    formula: "频率调节",
    rarity: "rare",
    effect: {"choice":{"high":{"soundBonus":10},"low":{"soundBonus":10,"extendTurns":2}}}
  },
  {
    id: "S10",
    name: "共振蓄能",
    type: "support",
    domain: ["声"],
    cost: 5,
    description: "恢复10精神力，若本回合打出声系攻击卡额外恢复5精神力。原理：共振蓄能——声波共振积累能量，蓄能越多释放越大。",
    formula: "共振",
    rarity: "common",
    effect: {"spiritRestore":10,"soundBonusSpirit":5}
  },
  {
    id: "S11",
    name: "隔音屏障",
    type: "support",
    domain: ["声"],
    cost: 16,
    description: "声系攻击伤害-35（持续2个己方回合）。原理：隔音材料吸收大部分声波能量，阻断声音传播。",
    formula: "隔音",
    rarity: "rare",
    effect: {"soundDefense":35,"turns":2}
  },
  {
    id: "S12",
    name: "聚焦声束",
    type: "support",
    domain: ["声"],
    cost: 11,
    description: "己方下次声系攻击+20伤害；若对方场上有隔音屏障，额外+10伤害。原理：凹面镜/声透镜聚焦声波——能量集中使声波强度提升。",
    formula: "声波聚焦",
    rarity: "common",
    effect: {"nextSoundBonus":20,"antiBarrier":10}
  },
  {
    id: "S13",
    name: "多普勒探测",
    type: "support",
    domain: ["声"],
    cost: 8,
    description: "查看己方牌库最上方5张牌，并可改变其排序。原理：多普勒雷达/声纳——通过频率变化探测目标位置和速度，预见即将到来的牌。",
    formula: "多普勒效应",
    rarity: "common",
    effect: {"scry":5}
  },
  {
    id: "S14",
    name: "滤光",
    type: "support",
    domain: ["光"],
    cost: 10,
    description: "己方选择一种领域。本回合己方打出该领域卡牌时精神力消耗-3，持续1个己方回合。原理：滤光片只允许特定波长的光通过——选定领域使该领域能量更纯粹，消耗更低。",
    formula: "滤光",
    rarity: "common",
    effect: {"filterDomain":true,"costReduction":3}
  },
  {
    id: "S15",
    name: "偏振过滤",
    type: "support",
    domain: ["光"],
    cost: 14,
    description: "对方下回合只能打出攻击卡或辅助卡中的一种（对手自选允许通过的类型，另一种无法打出）。原理：偏振片只允许特定方向的光通过——对手只能选择一种方向出牌。",
    formula: "偏振",
    rarity: "common",
    effect: {"polarize":true}
  },
  {
    id: "S16",
    name: "光速传播",
    type: "support",
    domain: ["光"],
    cost: 14,
    description: "打出后持续2个己方回合，己方可以在对方回合使用光领域卡牌，精神力消耗+3。原理：光速c=3×10⁸m/s不可超越——你的反应比对方出牌还快。",
    formula: "光速",
    rarity: "rare",
    effect: {"lightSpeed":true,"turns":2,"extraCost":3}
  },
  {
    id: "S17",
    name: "光谱叠加",
    type: "support",
    domain: ["光"],
    cost: 8,
    description: "打出后持续至本回合结束。己方本回合累计打出的不同领域种类数×10，后续所有攻击卡伤害+此值。原理：七色光叠加——越多波长叠加，白光越强。",
    formula: "光谱叠加",
    rarity: "common",
    effect: {"spectrum":true,"perDomain":10}
  },
  {
    id: "S18",
    name: "X射线透视",
    type: "support",
    domain: ["光"],
    cost: 14,
    description: "查看对方全部手牌 + 己方选择其中1张，将该卡弃置（进入对方弃牌堆）。原理：X射线透视看清底牌，精确定位摧毁关键牌。",
    formula: "X射线",
    rarity: "rare",
    effect: {"viewHand":"all","discardOpponent":1}
  },
  {
    id: "S19",
    name: "镜面迷宫",
    type: "support",
    domain: ["光"],
    cost: 16,
    description: "对方接下来3次出牌（仅出牌阶段），每次35%概率失败。失败时卡牌失效（效果不触发，卡牌进入弃牌堆，精神力消耗返还50%）。3次机会用完后此卡从场上消失。原理：平面镜多次反射使无数虚像与实物交织，受迷宫干扰无法精准发动。",
    formula: "平面镜反射",
    rarity: "epic",
    effect: {"mirrorMaze":true,"tries":3,"failChance":0.35,"isFieldCard":true}
  },
  {
    id: "S20",
    name: "影子束缚",
    type: "support",
    domain: ["光"],
    cost: 10,
    description: "若对方场上有卡牌存在，对方下2个回合无法打出辅助卡。若对方场上无卡牌，此卡无法打出。原理：光沿直线传播——对方场上卡牌遮挡光线形成影子，对方辅助卡被困在影子中。",
    formula: "光的直线传播",
    rarity: "rare",
    effect: {"shadowBind":true,"turns":2}
  },
  {
    id: "S21",
    name: "凸透成像",
    type: "support",
    domain: ["光"],
    cost: 12,
    description: "选择对手上一回合打出的一张攻击卡或辅助卡。实像（倒立放大）：将所选攻击卡造成的伤害转化为己方HP恢复，恢复量=该伤害×150%；虚像（正立放大）：复制该卡效果打出，伤害×120%，需额外支付该卡原精神力消耗的50%。原理：凸透镜成像——实像倒立放大使伤害反转增幅；虚像正立放大使复制效果增幅。",
    formula: "凸透镜成像",
    rarity: "rare",
    effect: {"convexLens":{"realImage":{"restoreHp":1.5},"virtualImage":{"copyEffect":1.2,"extraCost":0.5}}}
  },
  {
    id: "S22",
    name: "比热护盾",
    type: "support",
    domain: ["热"],
    cost: 14,
    description: "3个己方回合内免疫灼烧伤害（灼烧仍可附加且正常衰减层数，但每层灼烧不造成伤害）。原理：比热容c大使温度变化ΔT小，灼烧无效。",
    formula: "比热容",
    rarity: "rare",
    effect: {"burnImmune":true,"turns":3}
  },
  {
    id: "S23",
    name: "热机驱动",
    type: "support",
    domain: ["热"],
    cost: 0,
    description: "消耗2层灼烧，立即恢复15点精神力。原理：内能转化为机械能，消耗灼烧能量驱动热机做功。",
    formula: "热机",
    rarity: "rare",
    condition: "消耗对方2层灼烧",
    effect: {"consumeBurn":2,"spiritRestore":15}
  },
  {
    id: "S24",
    name: "温度升高",
    type: "support",
    domain: ["热"],
    cost: 6,
    description: "灼烧每层伤害从30提升至36，持续3个己方回合（期间新附加的灼烧同样受增幅）。原理：温度T升高使灼烧更猛烈；已热物体再加热升温更快。",
    formula: "温度升高",
    rarity: "rare",
    effect: {"burnEnhancePerDmg":36,"turns":3}
  },
  {
    id: "S25",
    name: "潜热释放",
    type: "support",
    domain: ["热"],
    cost: 0,
    description: "消耗2层灼烧，恢复80HP + 选择清除己方1种负面状态。原理：相变潜热吸收热能——偷灼烧能量恢复+净化。",
    formula: "潜热",
    rarity: "epic",
    condition: "消耗对方2层灼烧",
    effect: {"consumeBurn":2,"heal":80,"clearDebuff":1}
  },
  {
    id: "S26",
    name: "热量聚集",
    type: "support",
    domain: ["热"],
    cost: 10,
    description: "为对方附加3层灼烧。原理：温差大则传热快，热量聚集使灼烧加剧。",
    formula: "热传递",
    rarity: "common",
    effect: {"burn":3}
  },
  {
    id: "S27",
    name: "电阻屏障",
    type: "support",
    domain: ["电"],
    cost: 10,
    description: "受到的电系伤害-20（持续3个己方回合）。原理：电阻R升高使电流I降低（欧姆定律I=U/R），减伤效果更持久。",
    formula: "欧姆定律",
    rarity: "rare",
    effect: {"electricDefense":20,"turns":3}
  },
  {
    id: "S28",
    name: "电磁感应",
    type: "support",
    domain: ["电"],
    cost: 6,
    description: "持续3个己方回合。每回合获得2点精神力；场上期间，你每打出1张其他电系卡，获得2点精神力。原理：电磁感应现象——变化的磁场产生电流，将磁能转化为电能。",
    formula: "电磁感应",
    rarity: "common",
    effect: {"spiritPerTurn":2,"perElectricCard":2,"turns":3}
  },
  {
    id: "S29",
    name: "静电吸附",
    type: "support",
    domain: ["电"],
    cost: 8,
    description: "弃1张手牌，抽2张牌，清除己方1种负面状态（本回合生效）。原理：静电吸附有害粒子清除污染，净化负面状态。",
    formula: "静电",
    rarity: "common",
    effect: {"discard":1,"draw":2,"clearDebuff":1}
  },
  {
    id: "S30",
    name: "短路开关",
    type: "support",
    domain: ["电"],
    cost: 6,
    description: "牺牲场上1张电系辅助卡，本回合每张电系攻击卡额外+20伤害（本回合生效）。原理：短路使电流绕过负载直接导通，瞬间大电流爆发输出。",
    formula: "短路",
    rarity: "rare",
    effect: {"sacrificeElectricSupport":1,"perElectricAtkBonus":20}
  },
  {
    id: "S31",
    name: "高压击穿",
    type: "support",
    domain: ["电"],
    cost: 10,
    description: "己方电系攻击无视20点本领域防御（持续3个己方回合）。原理：电压大于击穿电压时绝缘体变导体，防御失效。",
    formula: "高压击穿",
    rarity: "common",
    effect: {"ignoreElectricDefense":20,"turns":3}
  },
  {
    id: "S32",
    name: "低压启动",
    type: "support",
    domain: ["电"],
    cost: 6,
    description: "选择手牌中1张电系卡，该卡精神力消耗-3（本回合生效）。原理：低电压即可启动，降低出牌门槛。",
    formula: "低压启动",
    rarity: "common",
    effect: {"reduceElectricCost":3}
  },
  {
    id: "S33",
    name: "多路放电",
    type: "support",
    domain: ["电"],
    cost: 6,
    description: "本回合所有电系攻击卡精神力消耗-2（本回合生效）。原理：多路并联放电使每条支路电阻降低，出牌门槛降低。",
    formula: "并联电路",
    rarity: "common",
    effect: {"reduceAllElectricCost":2}
  },
  {
    id: "S34",
    name: "置换卡",
    type: "support",
    domain: ["通用"],
    cost: 3,
    description: "将一张手牌放回牌库顶部，从牌库抽一张新牌（通用卡，不受任何领域加成）。原理：控制变量法——替换不合实验条件的变量。",
    formula: "控制变量法",
    rarity: "rare",
    effect: {"replaceHand":true}
  },
  {
    id: "D01",
    name: "力之领域·引力场",
    type: "domain",
    domain: ["力"],
    cost: 20,
    description: "力系攻击卡即时伤害+25，延续伤害+5，持续3个己方回合。原理：引力场无处不在——质量越大力场越强，力系效果全面增幅。",
    formula: "引力场",
    rarity: "rare",
    effect: {"forceDmgBonus":25,"forceDotBonus":5,"turns":3}
  },
  {
    id: "D02",
    name: "声之领域·共鸣场",
    type: "domain",
    domain: ["声"],
    cost: 20,
    description: "场上每有一张持续生效的声系卡（含声场效果），声系攻击伤害+8，持续4个己方回合。原理：共鸣腔放大声音——场上声系卡越多即共振面越多，增幅越大。",
    formula: "共鸣",
    rarity: "rare",
    effect: {"perSoundFieldBonus":8,"turns":4}
  },
  {
    id: "D03",
    name: "光之领域·棱镜界",
    type: "domain",
    domain: ["光"],
    cost: 20,
    description: "对方每张卡20%概率失效（效果不触发，精神力消耗返还50%），持续3个己方回合。原理：棱镜使光产生多次折射和反射——光路被持续干扰，出牌也可能落空。",
    formula: "棱镜折射",
    rarity: "rare",
    effect: {"opponentFailChance":0.2,"turns":3}
  },
  {
    id: "D04",
    name: "热之领域·熵增域",
    type: "domain",
    domain: ["热"],
    cost: 20,
    description: "对方每有1层灼烧，热系攻击伤害+4；当D04在场时，热系攻击卡附加的灼烧层数额外+1，持续3个己方回合。原理：熵增不可逆——灼烧越多无序度越高攻击越猛烈，形成正反馈。",
    formula: "熵增",
    rarity: "rare",
    effect: {"perBurnBonus":4,"extraBurn":1,"turns":3}
  },
  {
    id: "D05",
    name: "电之领域·电磁域",
    type: "domain",
    domain: ["电"],
    cost: 20,
    description: "麻痹在对方回合开始时，每点强度额外造成25伤害（叠加基础15伤害，共40/层），持续3个己方回合。原理：电磁场增强——麻痹放电更猛烈，电击伤害大幅提升。",
    formula: "电磁场",
    rarity: "rare",
    effect: {"paralysisBonusDmg":25,"turns":3}
  },
  {
    id: "C01",
    name: "芝诺龟",
    type: "summon",
    domain: ["力学神兽"],
    cost: 22,
    description: "对方每回合第一次攻击伤害减半。原理：芝诺悖论——阿基里斯追不上乌龟，看似无限接近却总有半步之遥。",
    hp: 360,
    maxHp: 360,
    formula: "芝诺悖论",
    rarity: "mythic",
    effect: {"halveFirstAttack":true}
  },
  {
    id: "C02",
    name: "麦克斯韦妖",
    type: "summon",
    domain: ["热学神兽"],
    cost: 25,
    description: "己方每回合+9精神力，每打出一张卡额外+2精神力（若精神力已满则+30HP）。原理：麦克斯韦妖分离快慢分子提取能量，持续产能。",
    hp: 270,
    maxHp: 270,
    formula: "麦克斯韦妖",
    rarity: "mythic",
    effect: {"spiritPerTurn":9,"spiritPerCard":2,"overflowHeal":30}
  },
  {
    id: "C03",
    name: "拉普拉斯妖",
    type: "summon",
    domain: ["力学神兽"],
    cost: 25,
    description: "己方每回合可预览对方牌库最上方5张并排序。原理：已知所有初始条件可预测未来——信息即力量。",
    hp: 240,
    maxHp: 240,
    formula: "拉普拉斯妖",
    rarity: "mythic",
    effect: {"scryOpponent":5}
  },
  {
    id: "C04",
    name: "薛定谔的猫",
    type: "summon",
    domain: ["量子神兽"],
    cost: 28,
    description: "己方出牌阶段开始时，50%概率造成100伤害，50%概率恢复100HP（若己方HP已满则恢复30精神力）。原理：量子叠加态——未观测前同时处于两种状态。",
    hp: 250,
    maxHp: 250,
    formula: "量子叠加",
    rarity: "mythic",
    effect: {"schrodinger":true,"dmg":100,"heal":100,"overflowSpirit":30}
  },
  {
    id: "C05",
    name: "牛顿",
    type: "summon",
    domain: ["力"],
    cost: 22,
    description: "力系攻击卡额外+20伤害。原理：F=ma——力越大效果越猛，经典力学的奠基人。",
    hp: 310,
    maxHp: 310,
    formula: "F=ma",
    rarity: "legendary",
    effect: {"forceDmgBonus":20}
  },
  {
    id: "C06",
    name: "阿基米德",
    type: "summon",
    domain: ["力"],
    cost: 22,
    description: "辅助卡精神力消耗-4，力系辅助卡额外-2。原理：杠杆原理——给我一个支点，我能撬动地球，省力不省功。",
    hp: 320,
    maxHp: 320,
    formula: "杠杆原理",
    rarity: "legendary",
    effect: {"supportCostReduction":4,"forceSupportExtra":2}
  },
  {
    id: "C07",
    name: "欧姆",
    type: "summon",
    domain: ["电"],
    cost: 26,
    description: "电系卡精神力消耗-6。原理：欧姆定律I=U/R——降低电阻=降低消耗，电流畅通无阻。",
    hp: 300,
    maxHp: 300,
    formula: "欧姆定律",
    rarity: "legendary",
    effect: {"electricCostReduction":6}
  },
  {
    id: "C08",
    name: "焦耳",
    type: "summon",
    domain: ["热"],
    cost: 26,
    description: "热系攻击+12伤害；己方每回合+2精神力。原理：热功当量——热能持续转化为功，能量永不消失。",
    hp: 280,
    maxHp: 280,
    formula: "焦耳定律",
    rarity: "legendary",
    effect: {"heatDmgBonus":12,"spiritPerTurn":2}
  },
  {
    id: "C09",
    name: "伽利略",
    type: "summon",
    domain: ["光"],
    cost: 26,
    description: "光系攻击+8伤害；己方场上每有一张持续生效的辅助卡，光系攻击额外+3伤害。原理：望远镜——聚焦放大，辅助卡=透镜。",
    hp: 280,
    maxHp: 280,
    formula: "望远镜",
    rarity: "legendary",
    effect: {"lightDmgBonus":8,"perSupportLightBonus":3}
  },
  {
    id: "C10",
    name: "贝尔",
    type: "summon",
    domain: ["声"],
    cost: 26,
    description: "己方每回合查看对方1张手牌；声系攻击+10伤害。原理：电话——声音远距离传输信息，信息获取优势。",
    hp: 280,
    maxHp: 280,
    formula: "电话原理",
    rarity: "legendary",
    effect: {"viewHand":1,"soundDmgBonus":10}
  },
  {
    id: "C11",
    name: "惠更斯",
    type: "summon",
    domain: ["光"],
    cost: 22,
    description: "对方攻击己方时20%概率闪避（全领域）；光系攻击+10伤害。原理：波动说——光如波般难以捕捉，忽隐忽现。",
    hp: 300,
    maxHp: 300,
    formula: "惠更斯原理",
    rarity: "legendary",
    effect: {"dodgeChance":0.2,"lightDmgBonus":10}
  },
  {
    id: "C12",
    name: "赫兹",
    type: "summon",
    domain: ["声"],
    cost: 24,
    description: "声系攻击+8伤害；声系辅助卡持续回合+1。原理：频率Hz——振动越快影响越持久。",
    hp: 290,
    maxHp: 290,
    formula: "频率",
    rarity: "epic",
    effect: {"soundDmgBonus":8,"soundSupportExtend":1}
  },
  {
    id: "C13",
    name: "瓦特",
    type: "summon",
    domain: ["热"],
    cost: 24,
    description: "热系攻击+8伤害；对方每有1层灼烧，热系攻击额外+3伤害。原理：功率P=W/t——灼烧越多转化效率越高。",
    hp: 280,
    maxHp: 280,
    formula: "功率",
    rarity: "epic",
    effect: {"heatDmgBonus":8,"perBurnBonus":3}
  },
  {
    id: "C14",
    name: "安培",
    type: "summon",
    domain: ["电"],
    cost: 24,
    description: "电系攻击+8伤害；麻痹每点强度，电系攻击额外+2伤害。原理：电流强度I——电流越大效果越强。",
    hp: 280,
    maxHp: 280,
    formula: "电流",
    rarity: "epic",
    effect: {"electricDmgBonus":8,"perParalysisBonus":2}
  },
  {
    id: "T01",
    name: "能量守恒",
    type: "phase",
    domain: ["通用"],
    cost: 30,
    description: "将己方已损失HP的30%转化为精神力（最多恢复60点）。原理：能量不会消失，只会从一种形式转化为另一种形式——损失的HP变成精神力。",
    formula: "能量守恒",
    rarity: "legendary",
    effect: {"hpToSpirit":0.3,"maxSpiritGain":60}
  },
  {
    id: "T02",
    name: "临界突破",
    type: "phase",
    domain: ["通用"],
    cost: 25,
    description: "仅当己方HP<30%时可打出，本回合所有攻击伤害翻倍。原理：临界态——微小变化引发巨大相变，濒死状态下的终极爆发。",
    formula: "临界态",
    rarity: "legendary",
    condition: "己方HP<30%",
    effect: {"doubleDmg":true}
  },
  {
    id: "T03",
    name: "熵逆转",
    type: "phase",
    domain: ["通用"],
    cost: 28,
    description: "与对手交换HP值；代价：己方精神力归零，对方精神力恢复至上限(100)。原理：熵增不可逆…但你做到了——违反热力学第二定律的终极幻想。",
    formula: "熵逆转",
    rarity: "legendary",
    effect: {"swapHP":true,"selfSpiritZero":true,"oppSpiritFull":true}
  }
];

export { CARDS };
